Q1: Create a 1D array of numbers from 0 to 9

In [2]:
import numpy as np

arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Q2: Create a 3×3 numpy array of all True’s

In [2]:
arr = np.full((3, 3), True, dtype=bool)
# alternative answer:
# np.ones((3,3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Q3: Extract all odd numbers from `arr`, which is a 1D array of numbers from 0 to 9

In [3]:
arr = np.arange(10)
odd = arr[arr % 2 == 1]
print(odd)

[1 3 5 7 9]


Q4: Replace all odd numbers in `arr` with -1

In [4]:
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Q5: Convert a 1D array (numbers from 0 to 9) to a 2D array with 2 rows

In [5]:
arr = np.arange(10)
# for reshape(), the new shape should be compatible with the original shape, so -1 here mean that
# it is 10/2 = 5
arr = arr.reshape(2, -1)  
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Q6: Stack arrays `a` and `b` vertically, where `a` is a 2D array filled with 1 with shape (2, 5), and `b` is a 2D array filled with 3 with shape (2, 5), set the dtype of both arrays with int16

In [6]:
a = np.ones((2,5), dtype=np.int16)
b = np.full((2,5), 3, dtype=np.int16) 
c = np.vstack([a, b])
print(c)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [3 3 3 3 3]
 [3 3 3 3 3]]


Q7: Stack the previously defined arrays `a` and `b` horizontally

In [7]:
d = np.hstack([a, b])
print(d)

[[1 1 1 1 1 3 3 3 3 3]
 [1 1 1 1 1 3 3 3 3 3]]


Q8: Get all items between 5 and 10 from `a`

In [3]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [4]:
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

Q9: Swap columns 1 and 2 in the array `arr`

In [10]:
arr = np.arange(9).reshape(3,3)

In [11]:
new_arr = arr[:, [1,0,2]]
print(new_arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


Q10: Swap rows 1 and 2 in the array `arr` we just defined

In [12]:
new_arr = arr[[1,0,2], :]
print(new_arr)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


Q11: Reverse the a 1D `arr` of numbers from 0 to 9

In [13]:
arr = np.arange(10)
new_arr = arr[::-1]
print(new_arr)

[9 8 7 6 5 4 3 2 1 0]


Q12: Create a 2D array of shape 5x3 to contain random float numbers between 0 and 20

In [14]:
arr = 20*np.random.random((5,3))
print(arr)

[[ 3.78056802 13.59820499  1.95680979]
 [16.90372794 11.95938918  0.8927939 ]
 [ 3.11029167 19.81544328  2.51540445]
 [16.23533949 12.42680576 11.11048631]
 [ 8.0719863  15.59923181 16.21154106]]


Q13: compute the sum of all elements in arr that you just created

In [15]:
sum = np.sum(arr)
print(sum)

154.1880239644456
